

name: Run tests and Lint

"on": push

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          npm i
          npm i eslint
          npm run build
  test:
    name: "test"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          npm run test
  lint:
    name: "lint"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          npm run lint
      
